import React, { createContext, useContext, useEffect, useState } from 'react';

export type Lang = 'en' | 'ur' | 'es' | 'ar' | 'ps' | 'sd';

type LangContextValue = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
};

const translations: Record<Lang, Record<string, string>> = {
  en: {
    home: 'Home',
    sign_in: 'Sign In',
    destinations: 'Destinations',
    profile: 'Profile',
    saved_itineraries: 'Saved Itineraries',
    admin_dashboard: 'Admin Dashboard',
    manage_bookings: 'Manage Bookings',
    manage_destinations: 'Manage Destinations',
    manage_itineraries: 'Manage Itineraries',
    manage_users: 'Manage Users',
    sign_out: 'Sign Out',
    trip_planner: 'Trip Planner',
    light_mode: 'Light',
    dark_mode: 'Dark',
    search: 'Search',
    clear_country: 'Clear country',
    price_filter: 'Price filter (base price)',
    tips: 'Tips',
    no_results: 'No results found',
    plan: 'Plan',
    source: 'From',
    source_placeholder: 'Select a city or airport',
    destinations_label: 'Destination',
    destination_placeholder: 'Type destination and press Enter or select from suggestions',
    budget_optional: 'Budget (optional)',
    budget_placeholder: 'Total budget (PKR)',
    start_date: 'Start Date',
    end_date: 'End Date',
    travellers: 'Travelers',
    travellers_placeholder: 'Number of people',
    ask_ai: 'Ask AI',
    plan_my_trip: 'Plan My Trip',
    hero_title: 'Plan Your Next Adventure',
    hero_sub: 'Get personalized itineraries, budgets, and recommendations.',
    explore_destinations: 'Explore Destinations',
    search_and_filter: 'Search and filter destinations by name, country, or price',
    search_by_name: 'Search by name or features...',
    country_region: 'Country / Region',
    all_countries: 'All Countries',
    ai_dialog_title: 'Your Perfect Trip Package ✈️',
    ai_dialog_sub: 'Complete itinerary within your budget',
    decline: 'Decline',
    book_all: 'Book All 🎉',
    budget_notes: 'Budget notes',
    options_within_budget: 'Options within your budget:',
    welcome_back: 'Welcome Back',
    sign_in_sub: 'Sign in to continue booking',
    create_account: 'Create Account',
    sign_up_sub: 'Sign up to start planning your trip',
    password: 'Password',
    at_least_8_chars: 'At least 8 characters',
    already_have_account: 'Already have an account? Sign in',
    forgot_password: 'Forgot password?',
    reset_password: 'Reset Password',
    enter_new_password: 'Enter your new password',
    new_password: 'New Password',
    confirm_password: 'Confirm Password',
    update_password: 'Update Password',
    email_confirmed: 'Email confirmed!',
    email_confirmed_msg: 'Your email has been confirmed. You can now sign in.',
    check_email: 'Check your email',
    password_reset_link: 'Password reset link sent.',
    email_not_confirmed: 'Email not confirmed',
    email_confirm_msg: 'Please confirm your email via the link sent.',
    sign_up: 'Sign up',
    updating: 'Updating...',
    saving: 'Saving...',
    loading: 'Loading...',
    my_account: 'My Account',
    my_bookings: 'My Bookings',
    admin_panel: 'Admin Panel',
    page_not_found: 'Page not found',
    page_not_found_desc: 'The page you\'re looking for doesn\'t exist. Let\'s get you back on track.',
    go_home: 'Go Home',
    plan_your_perfect_trip: 'Plan Your Perfect Trip',
    discover_destinations: 'Discover amazing destinations, create custom itineraries, and save your favorite trips',
    start_planning_now: 'Start Planning Now',
    explore_destinations_title: 'Explore Destinations',
    explore_destinations_desc: 'Browse hundreds of curated destinations from around the world',
    create_itineraries: 'Create Itineraries',
    create_itineraries_desc: 'Build custom day-by-day itineraries tailored to your preferences',
    budget_planning: 'Budget Planning',
    budget_planning_desc: 'Track costs and plan your trip within your budget constraints',
    ready_to_explore: 'Ready to explore?',
    start_building_adventure: 'Start building your next adventure with Trip Planner Pro',
    view_your_profile: 'View Your Profile',
    city_trip_planner: 'City Trip Planner',
    plan_perfect_adventure: 'Plan your perfect adventure',
    choose_destination: 'Choose Your Destination',
    select_city_begin: 'Select a city to begin planning',
    select_flight: 'Select Your Flight',
    departing_to: 'Departing for adventure',
    select_hotel: 'Select Your Hotel',
    curated_accommodations: 'Choose from our curated accommodations',
    itinerary: 'Itinerary',
    activities_dining: 'Activities and dining recommendations',
    booking_summary: 'Booking Summary',
    review_complete_trip: 'Review your complete trip',
    tell_us_dreams: 'Tell Us Your Dreams',
    select_destinations_date: 'Select destinations, set your dates, and define your budget.',
    ai_plans_trip: 'AI Plans Your Trip',
    ai_creates_personalized: 'Our AI creates personalized itineraries with flights, hotels, activities, and dining recommendations.',
    book_and_explore: 'Book & Explore',
    review_perfect_itinerary: 'Review your perfect itinerary, save it for later, or book immediately with our secure payment.',
    how_it_works: 'How It Works',
    three_simple_steps: 'Three simple steps to your perfect trip',
    travelers_count: 'Travelers',
    person: 'person',
    people: 'people',
    selected_flight: 'Selected Flight',
    selected_hotel: 'Selected Hotel',
    perfect_stays: 'Perfect Stays',
    perfect_stays_desc: 'Handpicked accommodations that match your style and budget.',
    local_flavors: 'Local Flavors',
    local_flavors_desc: 'Discover authentic dining experiences and local activities.',
    day_by_day_plans: 'Day-by-Day Plans',
    day_by_day_desc: 'Detailed itineraries with cost breakdowns.',
    confirmed_paid_bookings: 'Your confirmed and paid bookings',
    loading_bookings: 'Loading your bookings...',
    no_bookings_yet: 'No bookings yet',
    start_planning_adventure: 'Start planning your next adventure!',
    book_saved_itinerary: 'Book a Saved Itinerary',
    transaction_id: 'Transaction ID',
    total_amount: 'Total Amount',
    confirmed: 'Confirmed',
    details: 'Details',
    cancel: 'Cancel',
    cancel_booking: 'Cancel this booking? This action cannot be undone.',
    cancelled: 'Cancelled',
    cancelled_msg: 'Booking has been cancelled.',
    booking_details: 'Booking Details',
    view_load_edit: 'View, load, edit, or remove your previously saved trip plans',
    total_saved: 'Total Saved',
    refresh: 'Refresh',
    no_saved_yet: 'No saved itineraries yet',
    generate_save_trip: 'Generate and save a trip plan to see it here',
    start_planning_link: 'Start Planning',
    created: 'Created',
    total_price: 'Total Price',
    load: 'Load',
    book: 'Book',
    rename: 'Rename',
    itinerary_loaded: 'Loaded',
    itinerary_loaded_msg: 'Itinerary loaded into planner.',
    renamed: 'Renamed',
    itinerary_renamed: 'Itinerary title updated.',
    enter_new_title: 'Enter new itinerary title:',
    invalid_title: 'Invalid title',
    title_empty: 'Title cannot be empty.',
    saved_success: 'Saved',
    itinerary_saved: 'Itinerary saved successfully.',
    complete_payment: 'Complete Payment',
    secure_payment: 'Secure payment processing',
    demo_mode: 'Demo Mode',
    demo_info: 'Use any 16-digit card, future expiry date, and any 3-digit CVV.',
    order_summary: 'Order Summary',
    cardholder_name: 'Cardholder Name',
    card_number: 'Card Number',
    expiry_date: 'Expiry (MM/YY)',
    cvv: 'CVV',
    pay_now: 'Pay Now',
    processing: 'Processing...',
    payments_encrypted: 'Payments are encrypted and secure',
    edit_trip: 'Edit Trip',
    proceed_payment: 'Proceed to Payment',
    payment_successful: 'Payment Successful!',
    payment_confirmed: 'Your booking is confirmed.',
    sign_in_to_book: 'Sign in or sign up to proceed with booking',
    auth_required: 'Authentication Required',
    profile_details: 'Profile',
    profile_description: 'Manage your personal information and preferences',
    loading_profile: 'Loading profile...',
    profile_updated: 'Profile updated',
    profile_saved: 'Your profile was saved successfully.',
    account_management: 'Account Management',
    delete_profile_msg: 'Deleting your profile will remove all your personal data from the app.',
    account_removed: 'Account removed',
    account_removed_msg: 'Your profile has been removed from the app.',
    not_found_code: '404',
    return_home: 'Return to Home',
  },
  ur: {
    home: 'ہوم',
    sign_in: 'لاگ ان',
    destinations: 'مقامات',
    profile: 'پروفائل',
    saved_itineraries: 'محفوظ منصوبے',
    admin_dashboard: 'ایڈمن ڈیش بورڈ',
    manage_bookings: 'بکنگ مینج کریں',
    manage_destinations: 'مقامات منظم کریں',
    manage_itineraries: 'روٹس منظم کریں',
    manage_users: 'صارفین منظم کریں',
    sign_out: 'لاگ آؤٹ',
    trip_planner: 'ٹریپ پلانر',
    light_mode: 'روشنی',
    dark_mode: 'تاریک',
    search: 'تلاش',
    clear_country: 'ملک صاف کریں',
    price_filter: 'قیمت فلٹر',
    tips: 'نکات',
    no_results: 'کوئی نتیجہ نہیں',
    plan: 'منصوبہ',
    source: 'سے',
    source_placeholder: 'شہر یا ہوائی اڈہ درج کریں',
    destinations_label: 'کو',
    destination_placeholder: 'منزل درج کریں یا منتخب کریں',
    budget_optional: 'بجٹ',
    budget_placeholder: 'کل بجٹ',
    start_date: 'شروع',
    end_date: 'اختتام',
    travellers: 'مسافرین',
    travellers_placeholder: 'تعداد',
    ask_ai: 'AI سے پوچھیں',
    plan_my_trip: 'سفر منصوبہ کریں',
    hero_title: 'اگلا مہم منصوبہ کریں',
    hero_sub: 'ذاتی منصوبے حاصل کریں',
    explore_destinations: 'منزلیں تلاش کریں',
    search_and_filter: 'منزلوں کو تلاش کریں',
    search_by_name: 'نام سے تلاش',
    country_region: 'ملک',
    all_countries: 'تمام ملکیں',
    ai_dialog_title: 'بہترین سفر',
    ai_dialog_sub: 'مکمل منصوبہ',
    decline: 'انکار',
    book_all: 'سب بک کریں',
    budget_notes: 'بجٹ نوٹس',
    options_within_budget: 'اختیارات',
    welcome_back: 'خوش آمدید',
    sign_in_sub: 'لاگ ان کریں',
    create_account: 'اکاؤنٹ بنائیں',
    sign_up_sub: 'سائن اپ کریں',
    password: 'پاس ورڈ',
    at_least_8_chars: '8 حروف',
    already_have_account: 'اکاؤنٹ ہے؟',
    forgot_password: 'بھول گئے؟',
    reset_password: 'دوبارہ ترتیب',
    enter_new_password: 'نیا درج کریں',
    new_password: 'نیا',
    confirm_password: 'تصدیق کریں',
    update_password: 'اپ ڈیٹ کریں',
    email_confirmed: 'تصدیق شدہ',
    email_confirmed_msg: 'ای میل تصدیق ہو گئی',
    check_email: 'ای میل چیک کریں',
    password_reset_link: 'لنک بھیجی گئی',
    email_not_confirmed: 'تصدیق نہیں ہوئی',
    email_confirm_msg: 'براہ کرم تصدیق کریں',
    sign_up: 'سائن اپ',
    updating: 'اپ ڈیٹ ہو رہا ہے',
    saving: 'محفوظ ہو رہا ہے',
    loading: 'لوڈ ہو رہا ہے',
    my_account: 'میرا اکاؤنٹ',
    my_bookings: 'میری بکنگیں',
    admin_panel: 'ایڈمن پینل',
    page_not_found: 'صفحہ نہیں ملا',
    page_not_found_desc: 'صفحہ موجود نہیں',
    go_home: 'ہوم جائیں',
    plan_your_perfect_trip: 'بہترین سفر',
    discover_destinations: 'منزلیں دریافت کریں',
    start_planning_now: 'شروع کریں',
    explore_destinations_title: 'منزلیں دیکھیں',
    explore_destinations_desc: 'سینکڑوں منزلیں',
    create_itineraries: 'منصوبے بنائیں',
    create_itineraries_desc: 'اپنے منصوبے بنائیں',
    budget_planning: 'بجٹ منصوبہ',
    budget_planning_desc: 'اخراجات ٹریک کریں',
    ready_to_explore: 'تیار ہیں',
    start_building_adventure: 'مہم بنائیں',
    view_your_profile: 'پروفائل دیکھیں',
    city_trip_planner: 'شہر منصوبہ',
    plan_perfect_adventure: 'مہم منصوبہ کریں',
    choose_destination: 'منزل منتخب کریں',
    select_city_begin: 'شہر منتخب کریں',
    select_flight: 'پروازمنتخب کریں',
    departing_to: 'روانہ',
    select_hotel: 'ہوٹل منتخب کریں',
    curated_accommodations: 'رہائش گاہیں',
    itinerary: 'منصوبہ',
    activities_dining: 'سرگرمیاں',
    booking_summary: 'خلاصہ',
    review_complete_trip: 'سفر دیکھیں',
    tell_us_dreams: 'خوابیں بتائیں',
    select_destinations_date: 'منزلیں منتخب کریں',
    ai_plans_trip: 'AI منصوبہ بنائے',
    ai_creates_personalized: 'ذاتی منصوبے',
    book_and_explore: 'بک اور تلاش',
    review_perfect_itinerary: 'منصوبہ دیکھیں',
    how_it_works: 'کیسے کام کرتا ہے',
    three_simple_steps: 'تین قدم',
    travelers_count: 'مسافرین',
    person: 'شخص',
    people: 'لوگ',
    selected_flight: 'منتخب پروازیں',
    selected_hotel: 'منتخب ہوٹل',
    perfect_stays: 'بہترین ٹھہرنا',
    perfect_stays_desc: 'منتخب رہائش',
    local_flavors: 'مقامی ذائقے',
    local_flavors_desc: 'کھانے کی تجاویز',
    day_by_day_plans: 'روز منصوبے',
    day_by_day_desc: 'تفصیلی منصوبے',
    confirmed_paid_bookings: 'آپ کی بکنگیں',
    loading_bookings: 'لوڈ ہو رہی ہیں',
    no_bookings_yet: 'کوئی بکنگ نہیں',
    start_planning_adventure: 'منصوبہ کریں',
    book_saved_itinerary: 'محفوظ بک کریں',
    transaction_id: 'ٹرانزیکشن ID',
    total_amount: 'کل رقم',
    confirmed: 'تصدیق شدہ',
    details: 'تفصیلات',
    cancel: 'منسوخ کریں',
    cancel_booking: 'منسوخ کریں؟',
    cancelled: 'منسوخ',
    cancelled_msg: 'منسوخ ہو گئی',
    booking_details: 'تفصیلات',
    view_load_edit: 'منصوبے دیکھیں',
    total_saved: 'کل محفوظ',
    refresh: 'تازہ کریں',
    no_saved_yet: 'کوئی محفوظ نہیں',
    generate_save_trip: 'محفوظ کریں',
    start_planning_link: 'شروع کریں',
    created: 'بنایا گیا',
    total_price: 'کل قیمت',
    load: 'لوڈ کریں',
    book: 'بک کریں',
    rename: 'دوبارہ نام',
    itinerary_loaded: 'لوڈ ہوا',
    itinerary_loaded_msg: 'لوڈ ہوگیا',
    renamed: 'دوبارہ نام دیا',
    itinerary_renamed: 'عنوان اپ ڈیٹ ہوا',
    enter_new_title: 'عنوان درج کریں',
    invalid_title: 'غلط عنوان',
    title_empty: 'عنوان خالی نہیں',
    saved_success: 'محفوظ',
    itinerary_saved: 'محفوظ ہوگیا',
    complete_payment: 'ادائیگی مکمل',
    secure_payment: 'محفوظ ادائیگی',
    demo_mode: 'ڈیمو',
    demo_info: 'کوئی کارڈ استعمال کریں',
    order_summary: 'خلاصہ',
    cardholder_name: 'کارڈ ہولڈر',
    card_number: 'کارڈ نمبر',
    expiry_date: 'میعاد',
    cvv: 'CVV',
    pay_now: 'ابھی ادا کریں',
    processing: 'کارروائی جاری',
    payments_encrypted: 'محفوظ',
    edit_trip: 'ترمیم کریں',
    proceed_payment: 'آگے بڑھیں',
    payment_successful: 'کامیاب',
    payment_confirmed: 'تصدیق ہوگئی',
    sign_in_to_book: 'بکنگ جاری رکھنے سے پہلے سائن ان یا سائن اپ کریں',
    auth_required: 'توثیق ضروری ہے',
    profile_details: 'پروفائل',
    profile_description: 'معلومات منظم کریں',
    loading_profile: 'لوڈ ہو رہا ہے',
    profile_updated: 'اپ ڈیٹ ہوگیا',
    profile_saved: 'محفوظ ہوگیا',
    account_management: 'اکاؤنٹ منظم',
    delete_profile_msg: 'حذف کریں',
    account_removed: 'حذف ہوگیا',
    account_removed_msg: 'ہٹا دیا گیا',
    not_found_code: '404',
    return_home: 'ہوم جائیں',
  },
  es: {
    home: 'Inicio',
    sign_in: 'Iniciar',
    destinations: 'Destinos',
    profile: 'Perfil',
    saved_itineraries: 'Guardados',
    admin_dashboard: 'Admin',
    manage_bookings: 'Reservas',
    manage_destinations: 'Destinos',
    manage_itineraries: 'Itinerarios',
    manage_users: 'Usuarios',
    sign_out: 'Salir',
    trip_planner: 'Planificador',
    light_mode: 'Claro',
    dark_mode: 'Oscuro',
    search: 'Buscar',
    clear_country: 'Borrar',
    price_filter: 'Precio',
    tips: 'Consejos',
    no_results: 'Sin resultados',
    plan: 'Planificar',
    source: 'Origen',
    source_placeholder: 'Ciudad o aeropuerto',
    destinations_label: 'Destinos',
    destination_placeholder: 'Destino',
    budget_optional: 'Presupuesto',
    budget_placeholder: 'Presupuesto',
    start_date: 'Inicio',
    end_date: 'Fin',
    travellers: 'Viajeros',
    travellers_placeholder: 'Personas',
    ask_ai: 'Preguntar',
    plan_my_trip: 'Planificar',
    hero_title: 'Planifica tu Viaje',
    hero_sub: 'Obtén itinerarios',
    explore_destinations: 'Explora',
    search_and_filter: 'Busca destinos',
    search_by_name: 'Por nombre',
    country_region: 'País',
    all_countries: 'Todos',
    ai_dialog_title: 'Tu Viaje Perfecto',
    ai_dialog_sub: 'Itinerario',
    decline: 'Rechazar',
    book_all: 'Reservar',
    budget_notes: 'Presupuesto',
    options_within_budget: 'Opciones',
    welcome_back: 'Bienvenido',
    sign_in_sub: 'Inicia sesión',
    create_account: 'Crear Cuenta',
    sign_up_sub: 'Regístrate',
    password: 'Contraseña',
    at_least_8_chars: '8 caracteres',
    already_have_account: 'Ya tienes cuenta',
    forgot_password: 'Olvidaste',
    reset_password: 'Restablecer',
    enter_new_password: 'Nueva',
    new_password: 'Nueva',
    confirm_password: 'Confirmar',
    update_password: 'Actualizar',
    email_confirmed: 'Confirmado',
    email_confirmed_msg: 'Correo confirmado',
    check_email: 'Revisa',
    password_reset_link: 'Enlace enviado',
    email_not_confirmed: 'No confirmado',
    email_confirm_msg: 'Confirma tu correo',
    sign_up: 'Registrarse',
    updating: 'Actualizando',
    saving: 'Guardando',
    loading: 'Cargando',
    my_account: 'Mi Cuenta',
    my_bookings: 'Mis Reservas',
    admin_panel: 'Panel',
    page_not_found: 'No encontrada',
    page_not_found_desc: 'Página no existe',
    go_home: 'Inicio',
    plan_your_perfect_trip: 'Tu Viaje Perfecto',
    discover_destinations: 'Descubre destinos',
    start_planning_now: 'Comienza',
    explore_destinations_title: 'Explora',
    explore_destinations_desc: 'Cientos de destinos',
    create_itineraries: 'Crear itinerarios',
    create_itineraries_desc: 'Itinerarios personalizados',
    budget_planning: 'Presupuesto',
    budget_planning_desc: 'Controla costos',
    ready_to_explore: 'Listo',
    start_building_adventure: 'Comienza tu aventura',
    view_your_profile: 'Ver Perfil',
    city_trip_planner: 'Planificador',
    plan_perfect_adventure: 'Tu aventura',
    choose_destination: 'Elige destino',
    select_city_begin: 'Selecciona ciudad',
    select_flight: 'Vuelo',
    departing_to: 'Viajando',
    select_hotel: 'Hotel',
    curated_accommodations: 'Alojamientos',
    itinerary: 'Itinerario',
    activities_dining: 'Actividades',
    booking_summary: 'Resumen',
    review_complete_trip: 'Revisa',
    tell_us_dreams: 'Tus sueños',
    select_destinations_date: 'Selecciona',
    ai_plans_trip: 'AI Planifica',
    ai_creates_personalized: 'Itinerarios personalizados',
    book_and_explore: 'Reserva',
    review_perfect_itinerary: 'Revisa tu itinerario',
    how_it_works: 'Cómo funciona',
    three_simple_steps: 'Tres pasos',
    travelers_count: 'Viajeros',
    person: 'persona',
    people: 'personas',
    selected_flight: 'Vuelo',
    selected_hotel: 'Hotel',
    perfect_stays: 'Estadías',
    perfect_stays_desc: 'Alojamientos seleccionados',
    local_flavors: 'Sabores locales',
    local_flavors_desc: 'Experiencias locales',
    day_by_day_plans: 'Planes diarios',
    day_by_day_desc: 'Itinerarios detallados',
    confirmed_paid_bookings: 'Tus reservas',
    loading_bookings: 'Cargando',
    no_bookings_yet: 'Sin reservas',
    start_planning_adventure: 'Planifica',
    book_saved_itinerary: 'Reserva guardada',
    transaction_id: 'ID',
    total_amount: 'Total',
    confirmed: 'Confirmado',
    details: 'Detalles',
    cancel: 'Cancelar',
    cancel_booking: 'Cancelar',
    cancelled: 'Cancelado',
    cancelled_msg: 'Se canceló',
    booking_details: 'Detalles',
    view_load_edit: 'Ver planes',
    total_saved: 'Total guardado',
    refresh: 'Actualizar',
    no_saved_yet: 'Sin guardados',
    generate_save_trip: 'Guarda un plan',
    start_planning_link: 'Planificar',
    created: 'Creado',
    total_price: 'Precio total',
    load: 'Cargar',
    book: 'Reservar',
    rename: 'Renombrar',
    itinerary_loaded: 'Cargado',
    itinerary_loaded_msg: 'Se cargó',
    renamed: 'Renombrado',
    itinerary_renamed: 'Título actualizado',
    enter_new_title: 'Nuevo título',
    invalid_title: 'Inválido',
    title_empty: 'Vacío',
    saved_success: 'Guardado',
    itinerary_saved: 'Guardado exitosamente',
    complete_payment: 'Pago',
    secure_payment: 'Pago seguro',
    demo_mode: 'Demo',
    demo_info: 'Usa cualquier tarjeta',
    order_summary: 'Resumen',
    cardholder_name: 'Titular',
    card_number: 'Tarjeta',
    expiry_date: 'Vencimiento',
    cvv: 'CVV',
    pay_now: 'Pagar',
    processing: 'Procesando',
    payments_encrypted: 'Seguro',
    edit_trip: 'Editar',
    proceed_payment: 'Pagar',
    payment_successful: 'Exitoso',
    payment_confirmed: 'Confirmado',
    sign_in_to_book: 'Inicia sesión o regístrate para continuar con la reserva',
    auth_required: 'Autenticación requerida',
    profile_details: 'Perfil',
    profile_description: 'Tu información',
    loading_profile: 'Cargando',
    profile_updated: 'Actualizado',
    profile_saved: 'Guardado',
    account_management: 'Gestión',
    delete_profile_msg: 'Eliminar',
    account_removed: 'Eliminado',
    account_removed_msg: 'Se eliminó',
    not_found_code: '404',
    return_home: 'Inicio',
  },
  ar: {
    home: 'الرئيسية',
    sign_in: 'دخول',
    destinations: 'الوجهات',
    profile: 'الملف',
    saved_itineraries: 'المحفوظة',
    admin_dashboard: 'لوحة',
    manage_bookings: 'الحجوزات',
    manage_destinations: 'الوجهات',
    manage_itineraries: 'المسارات',
    manage_users: 'المستخدمون',
    sign_out: 'خروج',
    trip_planner: 'المخطط',
    light_mode: 'فاتح',
    dark_mode: 'داكن',
    search: 'بحث',
    clear_country: 'مسح',
    price_filter: 'السعر',
    tips: 'نصائح',
    no_results: 'لا نتائج',
    plan: 'خطط',
    source: 'من',
    source_placeholder: 'مدينة',
    destinations_label: 'إلى',
    destination_placeholder: 'الوجهة',
    budget_optional: 'الميزانية',
    budget_placeholder: 'الميزانية',
    start_date: 'البداية',
    end_date: 'النهاية',
    travellers: 'المسافرون',
    travellers_placeholder: 'الأشخاص',
    ask_ai: 'اسأل',
    plan_my_trip: 'خطط',
    hero_title: 'خطط لرحلتك',
    hero_sub: 'احصل على مسارات',
    explore_destinations: 'استكشف',
    search_and_filter: 'ابحث',
    search_by_name: 'بالاسم',
    country_region: 'البلد',
    all_countries: 'الكل',
    ai_dialog_title: 'رحلتك المثالية',
    ai_dialog_sub: 'مسار كامل',
    decline: 'رفض',
    book_all: 'احجز',
    budget_notes: 'الميزانية',
    options_within_budget: 'الخيارات',
    welcome_back: 'أهلا',
    sign_in_sub: 'دخول',
    create_account: 'حساب',
    sign_up_sub: 'تسجيل',
    password: 'كلمة المرور',
    at_least_8_chars: '8 أحرف',
    already_have_account: 'لديك حساب',
    forgot_password: 'نسيت',
    reset_password: 'إعادة تعيين',
    enter_new_password: 'كلمة جديدة',
    new_password: 'جديدة',
    confirm_password: 'تأكيد',
    update_password: 'تحديث',
    email_confirmed: 'مؤكد',
    email_confirmed_msg: 'البريد مؤكد',
    check_email: 'تحقق',
    password_reset_link: 'الرابط مرسل',
    email_not_confirmed: 'غير مؤكد',
    email_confirm_msg: 'أكد بريدك',
    sign_up: 'تسجيل',
    updating: 'تحديث',
    saving: 'حفظ',
    loading: 'تحميل',
    my_account: 'حسابي',
    my_bookings: 'حجوزاتي',
    admin_panel: 'اللوحة',
    page_not_found: 'غير موجودة',
    page_not_found_desc: 'الصفحة غير موجودة',
    go_home: 'الرئيسية',
    plan_your_perfect_trip: 'رحلتك المثالية',
    discover_destinations: 'اكتشف الوجهات',
    start_planning_now: 'ابدأ',
    explore_destinations_title: 'استكشف',
    explore_destinations_desc: 'مئات الوجهات',
    create_itineraries: 'أنشئ مسارات',
    create_itineraries_desc: 'مسارات مخصصة',
    budget_planning: 'تخطيط الميزانية',
    budget_planning_desc: 'تتبع التكاليف',
    ready_to_explore: 'مستعد',
    start_building_adventure: 'ابدأ مغامرتك',
    view_your_profile: 'ملفك',
    city_trip_planner: 'مخطط المدينة',
    plan_perfect_adventure: 'خطط لك',
    choose_destination: 'اختر',
    select_city_begin: 'اختر المدينة',
    select_flight: 'الرحلة',
    departing_to: 'المغادرة',
    select_hotel: 'الفندق',
    curated_accommodations: 'الإقامات',
    itinerary: 'المسار',
    activities_dining: 'الأنشطة',
    booking_summary: 'الملخص',
    review_complete_trip: 'راجع',
    tell_us_dreams: 'أحلامك',
    select_destinations_date: 'اختر',
    ai_plans_trip: 'الذكاء يخطط',
    ai_creates_personalized: 'مسارات مخصصة',
    book_and_explore: 'احجز واستكشف',
    review_perfect_itinerary: 'راجع المسار',
    how_it_works: 'كيفية العمل',
    three_simple_steps: 'ثلاث خطوات',
    travelers_count: 'المسافرون',
    person: 'شخص',
    people: 'أشخاص',
    selected_flight: 'الرحلة',
    selected_hotel: 'الفندق',
    perfect_stays: 'الإقامات المثالية',
    perfect_stays_desc: 'إقامات مختارة',
    local_flavors: 'النكهات المحلية',
    local_flavors_desc: 'تجارب محلية',
    day_by_day_plans: 'خطط يومية',
    day_by_day_desc: 'مسارات مفصلة',
    confirmed_paid_bookings: 'حجوزاتك',
    loading_bookings: 'تحميل',
    no_bookings_yet: 'لا حجوزات',
    start_planning_adventure: 'خطط',
    book_saved_itinerary: 'احجز محفوظ',
    transaction_id: 'معرف',
    total_amount: 'المبلغ الإجمالي',
    confirmed: 'مؤكد',
    details: 'التفاصيل',
    cancel: 'إلغاء',
    cancel_booking: 'ألغِ',
    cancelled: 'ملغى',
    cancelled_msg: 'تم الإلغاء',
    booking_details: 'التفاصيل',
    view_load_edit: 'اعرض المسارات',
    total_saved: 'إجمالي المحفوظ',
    refresh: 'تحديث',
    no_saved_yet: 'لا محفوظات',
    generate_save_trip: 'احفظ',
    start_planning_link: 'خطط',
    created: 'تم الإنشاء',
    total_price: 'السعر الإجمالي',
    load: 'تحميل',
    book: 'احجز',
    rename: 'إعادة تسمية',
    itinerary_loaded: 'تم التحميل',
    itinerary_loaded_msg: 'تم التحميل',
    renamed: 'تمت إعادة التسمية',
    itinerary_renamed: 'تم التحديث',
    enter_new_title: 'العنوان الجديد',
    invalid_title: 'غير صالح',
    title_empty: 'فارغ',
    saved_success: 'محفوظ',
    itinerary_saved: 'تم الحفظ بنجاح',
    complete_payment: 'إكمال الدفع',
    secure_payment: 'دفع آمن',
    demo_mode: 'وضع العرض',
    demo_info: 'استخدم أي بطاقة',
    order_summary: 'ملخص الطلب',
    cardholder_name: 'حامل البطاقة',
    card_number: 'رقم البطاقة',
    expiry_date: 'تاريخ الانتهاء',
    cvv: 'رمز CVV',
    pay_now: 'ادفع الآن',
    processing: 'معالجة',
    payments_encrypted: 'آمن',
    edit_trip: 'تعديل',
    proceed_payment: 'المضي',
    payment_successful: 'نجح الدفع',
    payment_confirmed: 'مؤكد',
    sign_in_to_book: 'قم بتسجيل الدخول أو إنشاء حساب قبل المتابعة مع الحجز',
    auth_required: 'المصادقة مطلوبة',
    profile_details: 'الملف الشخصي',
    profile_description: 'معلوماتك',
    loading_profile: 'تحميل',
    profile_updated: 'تم التحديث',
    profile_saved: 'تم الحفظ',
    account_management: 'إدارة الحساب',
    delete_profile_msg: 'حذف',
    account_removed: 'تم الحذف',
    account_removed_msg: 'تم الحذف',
    not_found_code: '404',
    return_home: 'الرئيسية',
  },
  ps: {
    home: 'کور',
    sign_in: 'داخل شوې',
    destinations: 'ملیمنځیې',
    profile: 'پروفائل',
    saved_itineraries: 'ذخیره شوې سفر',
    admin_dashboard: 'ادمین کنترول پینل',
    manage_bookings: 'بکنګ اداره کول',
    manage_destinations: 'ملیمنځیو اداره کول',
    manage_itineraries: 'سفر اداره کول',
    manage_users: 'کاروونکو اداره کول',
    sign_out: 'بهر شئ',
    trip_planner: 'سفر منصوبه کار',
    light_mode: 'روښانه',
    dark_mode: 'تور',
    search: 'لټون',
    source: 'له',
    source_placeholder: 'ښار یا فرودگاه وړاندې کړئ',
    destinations_label: 'منزل',
    destination_placeholder: 'منزل وړاندې کړئ',
    budget_optional: 'بودیجه (اختیاري)',
    budget_placeholder: 'ټول بودیجه (پي کې آر)',
    start_date: 'د شروعات نیټه',
    end_date: 'د پای نیټه',
    travellers: 'مسافران',
    travellers_placeholder: 'د خلکو شمیر',
    ask_ai: 'AI سے پوچھیں',
    plan_my_trip: 'زما سفر منصوبه کړئ',
    hero_title: 'خپل راتلونکې ماجرا منصوبه کړئ',
    hero_sub: 'شخصي سفر، بودیجه، او تجاویز ترلاسه کړئ۔',
    explore_destinations: 'ملیمنځیې وګرځیدئ',
    search_and_filter: 'ملیمنځیو نام، هیواد، یا قیمت لخوا لټون کړئ',
    search_by_name: 'نام یا ځانګړتیاوې لخوا لټون کړئ',
    country_region: 'هیواد / سیمه',
    all_countries: 'ټول هیوادونه',
    proceed_payment: 'تادیه کې مخکې وړاندې شئ',
    edit_trip: 'سفر سمون کړئ',
    complete_payment: 'تادیه مکمل کړئ',
    payment_successful: 'تادیه بریالۍ',
    profile_details: 'پروفائل تفصیلات',
    my_bookings: 'زما بکنګونه',
    not_found_code: '404',
  },
  sd: {
    home: 'گھر',
    sign_in: 'داخل ٿيو',
    destinations: 'منزلون',
    profile: 'پروفائل',
    saved_itineraries: 'محفوظ سفر',
    admin_dashboard: 'ايڈمن ڈيش بورڊ',
    manage_bookings: 'بکنگ منظم ڪريو',
    manage_destinations: 'منزلون منظم ڪريو',
    manage_itineraries: 'سفر منظم ڪريو',
    manage_users: 'صارفين منظم ڪريو',
    sign_out: 'ٻاهر نڪلو',
    trip_planner: 'سفر منصوبهڪار',
    light_mode: 'روشن',
    dark_mode: 'اونداهو',
    search: 'ڳولو',
    source: 'کان',
    source_placeholder: 'شهر يا فرودگاه درج ڪريو',
    destinations_label: 'منزل',
    destination_placeholder: 'منزل درج ڪريو',
    budget_optional: 'بجيٽ (اختياري)',
    budget_placeholder: 'ڪل بجيٽ (پي ڪے آر)',
    start_date: 'شروع ٿيڻ جي تاريخ',
    end_date: 'ختم ٿيڻ جي تاريخ',
    travellers: 'مسافر',
    travellers_placeholder: 'ماڻهن جو تعداد',
    ask_ai: 'AI کان پڇو',
    plan_my_trip: 'منهنجو سفر منصوبهڪاري',
    hero_title: 'پنهنجي ايندڙ سفر جو منصوبه بنايو',
    hero_sub: 'ذاتي نوعيت جا سفر، بجيٽ، ۽ سفارشون حاصل ڪريو۔',
    explore_destinations: 'منزلون دريافت ڪريو',
    search_and_filter: 'منزلون نالو، ملڪ، يا قيمت سان ڳولو',
    search_by_name: 'نالي يا خصوصيتن سان ڳولو',
    country_region: 'ملڪ / علاقو',
    all_countries: 'سڀ ملڪ',
    proceed_payment: 'ادائيگي جي طرف بڙھو',
    edit_trip: 'سفر ۾ ترميم ڪريو',
    complete_payment: 'ادائيگي مڪمل ڪريو',
    payment_successful: 'ادائيگي ڪامياب',
    profile_details: 'پروفائل جي تفصيلات',
    my_bookings: 'منهنجي بکنگز',
    not_found_code: '404',
  },
};

const LanguageContext = createContext<LangContextValue | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    try {
      const saved = localStorage.getItem('lang');
      return (saved as Lang) || 'en';
    } catch (e) {
      return 'en';
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem('lang', lang);
    } catch (e) {
      // ignore
    }
  }, [lang]);

  useEffect(() => {
    try {
      if (typeof document !== 'undefined' && document.documentElement) {
        document.documentElement.lang = lang;
        document.documentElement.setAttribute('data-lang', lang);
        // Direction is handled by App.css based on data-lang attribute
        // Do NOT set dir here - let CSS handle it
      }
    } catch (e) {
      // ignore
    }
  }, [lang]);

  const t = (key: string) => {
    return translations[lang]?.[key] ?? translations['en']?.[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: setLangState, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};

export default LanguageContext;
